# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'met_joint_widget.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QPushButton, QSizePolicy, QVBoxLayout, QWidget)

class Ui_METJointWidget(object):
    def setupUi(self, METJointWidget):
        if not METJointWidget.objectName():
            METJointWidget.setObjectName(u"METJointWidget")
        METJointWidget.resize(169, 25)
        METJointWidget.setStyleSheet(u"/*-----QScrollArea-----*/\n"
"QScrollArea\n"
"{\n"
"	border: 0px solid black; \n"
"	margin: 0px 0px 0px 0px;\n"
"	border-style:none;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLayout-----*/\n"
"QLayout\n"
"{\n"
"	border-style:none;\n"
"	border-radius: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"	background-color: transparent;\n"
"	color: #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QFrame-----*/\n"
"QFrame\n"
"{\n"
"	border-style:none;\n"
"	border-radius: 5px;\n"
"	background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"	background-color: transparent;\n"
"	color: #c2c7d5;\n"
"	font-size: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: hsv(187, 100%, 50%);\n"
"    color: hsv(0, 0, 50%);\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:1, "
                        "stop:0 hsv(187, 100%, 50%),stop:1 hsv(180, 100%, 70%));\n"
"}\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: hsv(180, 100%, 100%);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::checked\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: hsv(180, 100%, 90%);\n"
"}\n"
"QPushButton::checked::hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:1, stop:0 hsv(180, 100%, 90%),stop:1 hsv(180, 100%, 100%));\n"
"}\n"
"QPushButton::checked::pressed\n"
"{\n"
"    background-color: hsv(180, 100%, 100%);\n"
"}\n"
"\n"
"\n"
"/*-----QProgressBar-----*/\n"
"QProgressBar\n"
"{\n"
"	background-color: hsv(187, 100%, 70%);\n"
"	color: rgb(255, 255, 255);\n"
"	font-size: 13px;\n"
"	font-weight: bold;\n"
"	padding: -1px;\n"
"	border: none;\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar:chunk\n"
"{\n"
"	background-color: hsv(180, 100%, 90%);\n"
"	color: rgb(255, 255, 255);\n"
"	font-size: 20px;\n"
"	font-weight: bold;\n"
"	padding: -1px;\n"
"	border: none;"
                        "\n"
"	border-radius: 8px;\n"
"}\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"QCheckBox\n"
"{\n"
"	background-color: transparent;\n"
"	color: #fff;\n"
"	font-size: 10px;\n"
"	font-weight: bold;\n"
"	border: none;\n"
"	border-radius: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"QCheckBox::indicator\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid darkgray;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(\"./ressources/check.png\");\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));;\n"
"    border: 1px solid #607cff;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 1px solid #08b099;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"	color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"	background-color: #656565;\n"
"	colo"
                        "r: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit\n"
"{\n"
"	background-color: #c2c7d5;\n"
"	color: #000;\n"
"	font-weight: bold;\n"
"	border: none;\n"
"	border-radius: 2px;\n"
"	padding: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QListView-----*/\n"
"QListView\n"
"{\n"
"	background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(50, 61, 80, 255),stop:1 rgba(44, 49, 69, 255));\n"
"	color: #fff;\n"
"	font-size: 12px;\n"
"	font-weight: bold;\n"
"	border: 1px solid #191919;\n"
"	show-decoration-selected: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item\n"
"{\n"
"	color: #31cecb;\n"
"	background-color: #454e5e;\n"
"	border: none;\n"
"	padding: 5px;\n"
"	border-radius: 0px;\n"
"	padding-left : 10px;\n"
"	height: 42px;\n"
"\n"
"}\n"
"\n"
"QListView::item:selected\n"
"{\n"
"	color: #31cecb;\n"
"	background-color: #454e5e;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:!selected\n"
"{\n"
"	color:white;\n"
"	background-color: transparent;\n"
"	border: no"
                        "ne;\n"
"	padding-left : 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:!selected:hover\n"
"{\n"
"	color: #bbbcba;\n"
"	background-color: #454e5e;\n"
"	border: none;\n"
"	padding-left : 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTreeView-----*/\n"
"QTreeView \n"
"{\n"
"	background-color: #232939;\n"
"	show-decoration-selected: 0;\n"
"	color: #c2c8d7;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item \n"
"{\n"
"	border-top-color: transparent;\n"
"	border-bottom-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:hover \n"
"{\n"
"	background-color: #606060;\n"
"	color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:selected \n"
"{\n"
"	background-color: #0ab19a;\n"
"	color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:selected:active\n"
"{\n"
"	background-color: #0ab19a;\n"
"	color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings \n"
"{\n"
"	image: url(://tree-closed.png);\n"
"\n"
"}\n"
"\n"
"QTreeView::branch:open:has-childr"
                        "en:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  \n"
"{\n"
"	image: url(://tree-open.png);\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTableView & QTableWidget-----*/\n"
"QTableView\n"
"{\n"
"    background-color: #232939;\n"
"	border: 1px solid gray;\n"
"    color: #f0f0f0;\n"
"    gridline-color: #232939;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::disabled\n"
"{\n"
"    background-color: #242526;\n"
"    border: 1px solid #32414B;\n"
"    color: #656565;\n"
"    gridline-color: #656565;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:hover \n"
"{\n"
"    background-color: #606060;\n"
"    color: #f0f0f0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:selected \n"
"{\n"
"	background-color: #0ab19a;\n"
"    color: #F0F0F0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:selected:disabled\n"
"{\n"
"    background-color: #1a1b1c;\n"
"    border: 2px solid #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"{\n"
"	background-color: #343a49;\n"
""
                        "    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section\n"
"{\n"
"	color: #fff;\n"
"	border-top: 0px;\n"
"	border-bottom: 1px solid gray;\n"
"	border-right: 1px solid gray;\n"
"	background-color: #343a49;\n"
"    margin-top:1px;\n"
"	margin-bottom:1px;\n"
"	padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:disabled\n"
"{\n"
"    background-color: #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"{\n"
"    color: #fff;\n"
"    background-color: #0ab19a;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked:disabled\n"
"{\n"
"    color: #656565;\n"
"    background-color: #525251;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"QHeaderView::section::vertical::only-one\n"
"{\n"
"    border-top: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical\n"
"{\n"
"    border-top: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"QHeaderView::section::horizontal::only-one\n"
"{\n"
"    "
                        "border-left: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal\n"
"{\n"
"    border-left: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:horizontal \n"
"{\n"
"    background-color: transparent;\n"
"    height: 8px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"{\n"
"    border: none;\n"
"	min-width: 100px;\n"
"    background-color: #56576c;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal, \n"
"QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-page:horizontal, \n"
"QScrollBar::sub-page:horizontal \n"
"{\n"
"    width: 0px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical \n"
"{\n"
"    background-color: transparent;\n"
"    width: 8px;\n"
"    margin: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"{\n"
"    border: none;\n"
"	min-height: 100px;\n"
"    background-color: #56576c;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical"
                        ", \n"
"QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical \n"
"{\n"
"    height: 0px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"")
        self.verticalLayout = QVBoxLayout(METJointWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.fixable_joint_frame = QFrame(METJointWidget)
        self.fixable_joint_frame.setObjectName(u"fixable_joint_frame")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixable_joint_frame.sizePolicy().hasHeightForWidth())
        self.fixable_joint_frame.setSizePolicy(sizePolicy)
        self.fixable_joint_frame.setFrameShape(QFrame.StyledPanel)
        self.fixable_joint_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_10 = QHBoxLayout(self.fixable_joint_frame)
        self.horizontalLayout_10.setSpacing(1)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.fixable_joint_label = QLabel(self.fixable_joint_frame)
        self.fixable_joint_label.setObjectName(u"fixable_joint_label")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.fixable_joint_label.sizePolicy().hasHeightForWidth())
        self.fixable_joint_label.setSizePolicy(sizePolicy1)

        self.horizontalLayout_10.addWidget(self.fixable_joint_label)

        self.fixable_joint_x_button = QPushButton(self.fixable_joint_frame)
        self.fixable_joint_x_button.setObjectName(u"fixable_joint_x_button")
        self.fixable_joint_x_button.setMinimumSize(QSize(25, 25))
        self.fixable_joint_x_button.setMaximumSize(QSize(25, 25))
        self.fixable_joint_x_button.setCheckable(True)
        self.fixable_joint_x_button.setChecked(True)

        self.horizontalLayout_10.addWidget(self.fixable_joint_x_button)

        self.fixable_joint_y_button = QPushButton(self.fixable_joint_frame)
        self.fixable_joint_y_button.setObjectName(u"fixable_joint_y_button")
        self.fixable_joint_y_button.setMinimumSize(QSize(25, 25))
        self.fixable_joint_y_button.setMaximumSize(QSize(25, 25))
        self.fixable_joint_y_button.setCheckable(True)
        self.fixable_joint_y_button.setChecked(True)

        self.horizontalLayout_10.addWidget(self.fixable_joint_y_button)

        self.fixable_joint_z_button = QPushButton(self.fixable_joint_frame)
        self.fixable_joint_z_button.setObjectName(u"fixable_joint_z_button")
        self.fixable_joint_z_button.setMinimumSize(QSize(25, 25))
        self.fixable_joint_z_button.setMaximumSize(QSize(25, 25))
        self.fixable_joint_z_button.setCheckable(True)
        self.fixable_joint_z_button.setChecked(True)

        self.horizontalLayout_10.addWidget(self.fixable_joint_z_button)


        self.verticalLayout.addWidget(self.fixable_joint_frame)


        self.retranslateUi(METJointWidget)

        QMetaObject.connectSlotsByName(METJointWidget)
    # setupUi

    def retranslateUi(self, METJointWidget):
        METJointWidget.setWindowTitle(QCoreApplication.translate("METJointWidget", u"Form", None))
        self.fixable_joint_label.setText(QCoreApplication.translate("METJointWidget", u"thrgh_fwd_rwr_r", None))
        self.fixable_joint_x_button.setText(QCoreApplication.translate("METJointWidget", u"x", None))
        self.fixable_joint_y_button.setText(QCoreApplication.translate("METJointWidget", u"y", None))
        self.fixable_joint_z_button.setText(QCoreApplication.translate("METJointWidget", u"z", None))
    # retranslateUi

